# Generated by Django 4.2.7 on 2023-12-01 22:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gameroom', '0001_initial'),
        ('users', '0002_pamplesneakinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameroomInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('games_played', models.IntegerField(default=0)),
                ('wins', models.IntegerField(default=0)),
                ('loses', models.IntegerField(default=0)),
                ('current_game', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='player_current_game', to='gameroom.player')),
                ('previous_games', models.ManyToManyField(blank=True, related_name='player_previous_games', to='gameroom.player')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='gameroom_info', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='PamplesneakInfo',
        ),
    ]
