# Generated by Django 4.2.7 on 2023-12-01 23:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gameroom', '0001_initial'),
        ('users', '0003_gameroominfo_delete_pamplesneakinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameroominfo',
            name='current_game',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='player_current_game', to='gameroom.game'),
        ),
        migrations.AlterField(
            model_name='gameroominfo',
            name='previous_games',
            field=models.ManyToManyField(blank=True, related_name='player_previous_games', to='gameroom.game'),
        ),
    ]
