# Generated by Django 4.2.7 on 2023-12-01 23:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gameroom', '0001_initial'),
        ('users', '0004_alter_gameroominfo_current_game_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GameroomInfo',
            new_name='UserProfile',
        ),
    ]
