# Generated by Django 4.2.7 on 2023-12-01 23:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gameroom', '0001_initial'),
        ('users', '0005_rename_gameroominfo_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='current_player',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_player', to='gameroom.player'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='previous_players',
            field=models.ManyToManyField(blank=True, related_name='previous_players', to='gameroom.player'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
