# fly.toml app configuration file generated for pamplesneak on 2023-12-23T18:00:35-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "pamplesneak"
primary_region = "yyz"
console_command = "/code/manage.py shell"

[build]

[deploy]
  release_command = "sh -c 'python manage.py migrate --noinput && python manage.py loaddata data/examplewords.json --ignore-conflicts || true'"

[env]
  PORT = "8000"
  DEBUG = "false"

[processes]
  app = "sh -c 'celery -A pamplesneak worker -l info --detach && daphne -b 0.0.0.0 -p 8000 pamplesneak.asgi:application'"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 512

[mounts]
  source = "pamplesneak_data"
  destination = "/data"

[[statics]]
  guest_path = "/code/static"
  url_prefix = "/static/"
