# Generated by Django 4.2.7 on 2023-12-02 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameroom', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
