# Generated by Django 4.2.7 on 2023-12-02 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameroom', '0002_word_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='successful',
            field=models.BooleanField(null=True),
        ),
    ]
