# Generated by Django 4.2.7 on 2023-12-03 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameroom', '0003_word_successful'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='received_sneaks',
            field=models.IntegerField(default=0),
        ),
    ]
