# Generated by Django 4.2.7 on 2023-12-03 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameroom', '0004_player_received_sneaks'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='rejections_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='word',
            name='validation_count',
            field=models.IntegerField(default=0),
        ),
    ]
