# Generated by Django 4.2.7 on 2023-12-03 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gameroom', '0005_word_rejections_count_word_validation_count'),
    ]

    operations = [
        migrations.RenameField(
            model_name='word',
            old_name='validation_count',
            new_name='validations_count',
        ),
    ]
