# Generated by Django 4.2.7 on 2023-12-03 22:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gameroom', '0007_vote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='gameroom.player'),
        ),
    ]
