# Generated by Django 4.2.7 on 2023-12-03 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameroom', '0008_alter_vote_player'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='skipped',
            field=models.BooleanField(null=True),
        ),
    ]
