# Generated by Django 4.2.7 on 2023-12-23 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameroom', '0009_word_skipped'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExampleWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=64)),
                ('category', models.CharField(max_length=64)),
                ('difficulty', models.IntegerField(default=0)),
            ],
        ),
        migrations.AlterField(
            model_name='game',
            name='number_of_players',
            field=models.IntegerField(default=1),
        ),
    ]
