# Generated by Django 4.2.7 on 2023-12-23 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameroom', '0010_exampleword_alter_game_number_of_players'),
    ]

    operations = [
        migrations.AddField(
            model_name='exampleword',
            name='note',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
