# Generated by Django 4.2.7 on 2023-12-23 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameroom', '0011_exampleword_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exampleword',
            name='note',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='exampleword',
            name='word',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='word',
            name='word',
            field=models.CharField(max_length=128),
        ),
    ]
