# Generated by Django 4.2.7 on 2023-12-24 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameroom', '0012_alter_exampleword_note_alter_exampleword_word_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='game_room_code',
            field=models.CharField(default='Happy1', max_length=6),
            preserve_default=False,
        ),
    ]
