# Generated by Django 4.2.7 on 2023-12-24 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameroom', '0013_game_game_room_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='game_room_code',
            field=models.CharField(max_length=6, unique=True),
        ),
    ]
