# Generated by Django 4.2.7 on 2024-01-06 03:03

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gameroom', '0014_alter_game_game_room_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='number_of_rounds',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12)], default=1),
        ),
        migrations.CreateModel(
            name='Round',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_number', models.IntegerField()),
                ('duration', models.DurationField(default=datetime.timedelta(seconds=300))),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rounds', to='gameroom.game')),
            ],
        ),
    ]
