# Generated by Django 4.2.7 on 2024-01-06 19:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameroom', '0015_game_number_of_rounds_round'),
    ]

    operations = [
        migrations.AddField(
            model_name='round',
            name='allow_additional_sneaks',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='round',
            name='sneaks_per_round',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='round',
            name='time_between_rounds',
            field=models.DurationField(default=datetime.timedelta(seconds=300)),
        ),
    ]
