# Generated by Django 4.2.7 on 2024-01-06 19:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameroom', '0016_round_allow_additional_sneaks_round_sneaks_per_round_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='current_round',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='round',
            name='sneaks_per_round',
            field=models.IntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='round',
            name='time_between_rounds',
            field=models.DurationField(default=datetime.timedelta(seconds=180)),
        ),
    ]
