# Generated by Django 4.2.7 on 2024-01-07 00:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gameroom', '0017_game_current_round_alter_round_sneaks_per_round_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='host',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='host_game', to='gameroom.player'),
        ),
    ]
