# Generated by Django 4.2.7 on 2024-01-07 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameroom', '0019_alter_game_host'),
    ]

    operations = [
        migrations.AddField(
            model_name='round',
            name='ended',
            field=models.BooleanField(default=False),
        ),
    ]
