# Generated by Django 4.2.7 on 2024-01-07 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameroom', '0020_round_ended'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='state',
            field=models.CharField(choices=[('create', 'create'), ('play', 'play')], default='creation', max_length=10),
        ),
    ]
