# Generated by Django 4.2.7 on 2024-01-07 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameroom', '0021_game_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='ended',
            field=models.BooleanField(default=False),
        ),
    ]
