# Generated by Django 4.2.7 on 2024-01-09 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameroom', '0022_game_ended'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='state',
        ),
        migrations.AddField(
            model_name='round',
            name='state',
            field=models.CharField(choices=[('transition', 'transition'), ('create', 'create'), ('play', 'play')], default='transition', max_length=10),
        ),
    ]
