# Generated by Django 4.2.7 on 2024-01-09 01:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameroom', '0023_remove_game_state_round_state'),
    ]

    operations = [
        migrations.RenameField(
            model_name='round',
            old_name='time_between_rounds',
            new_name='create_state_duration',
        ),
        migrations.RenameField(
            model_name='round',
            old_name='duration',
            new_name='play_state_duration',
        ),
        migrations.AddField(
            model_name='round',
            name='transition_state_duration',
            field=models.DurationField(default=datetime.timedelta(seconds=10)),
        ),
    ]
