# Generated by Django 4.2.7 on 2024-01-09 02:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gameroom', '0024_rename_time_between_rounds_round_create_state_duration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='round',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gameroom.round'),
        ),
    ]
