# Generated by Django 4.2.7 on 2024-01-10 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameroom', '0025_word_round'),
    ]

    operations = [
        migrations.AddField(
            model_name='round',
            name='state_start_time',
            field=models.DateTimeField(null=True),
        ),
    ]
