# Generated by Django 4.2.7 on 2024-01-10 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameroom', '0026_round_state_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='round',
            name='state_start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
