# Generated by Django 4.2.7 on 2024-01-11 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameroom', '0027_alter_round_state_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='round',
            name='state',
            field=models.CharField(choices=[('transition', 'transition'), ('create', 'create'), ('play', 'play'), ('end', 'end')], default='transition', max_length=10),
        ),
    ]
