# Generated by Django 4.2.7 on 2024-02-10 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameroom', '0028_alter_game_active_alter_round_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='time_completed',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
