# Generated by Django 4.2.7 on 2024-02-10 20:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gameroom', '0029_word_time_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='likes_count',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes_given', to='gameroom.player')),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='gameroom.word')),
            ],
            options={
                'unique_together': {('word', 'player')},
            },
        ),
    ]
